### ISSUE TITLE
Add regex support for mapping postprocessing

### ISSUE THREAD

**Issue by nuest** [nuest/youngs#2]
Add regex expressions the the post-processing options, similar to replacements:

```yaml
    themes:
        xpath: "//theme/text()"
        replacements:
            - replace: "theme.par."
              with: ""
        regexes:
            - r1: "^[^_]*_"
            - r2: "/\S+/g"
        properties:
            store: yes
            type: string
```

Given a an XML

```xml
<theme>theme_A:_very   good indeed  </theme><theme>theme_B:    -not-so_good</theme>
```

this should produce

```json
{ "themes": [ "A:verygood", "B:not-so_good" ] }
```
